import type { SpineDocument } from "./document.js";

type JsonRecord = Record<string, unknown>;
type Path = (string | number)[];

export interface SemanticDifference {
  path: string;
  staged: string;
  reexported: string;
}

export interface SemanticFidelity {
  differenceCount: number;
  differences: SemanticDifference[];
  differencesTruncated: boolean;
  numericTolerance: number;
  allowances: string[];
}

// Spine writes decimal values with limited precision. A fixed absolute tolerance
// avoids hiding proportional changes to large coordinates or curve controls.
const NUMERIC_TOLERANCE = 1e-4;
const MAX_DIFFERENCES = 100;
const OMIT = Symbol("omit");

function record(value: unknown): value is JsonRecord {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function equalNumber(left: unknown, right: number): boolean {
  return typeof left === "number" && Math.abs(left - right) < NUMERIC_TOLERANCE;
}

function isDefault(value: unknown, fallback: unknown): boolean {
  return typeof fallback === "number" ? equalNumber(value, fallback) : value === fallback;
}

function isEmpty(value: unknown): boolean {
  return Array.isArray(value) ? value.length === 0 : record(value) && Object.keys(value).length === 0;
}

function defaultFor(parent: Path, field: string, source: JsonRecord, root: JsonRecord): unknown | typeof OMIT {
  const pick = (defaults: JsonRecord): unknown | typeof OMIT => Object.hasOwn(defaults, field) ? defaults[field] : OMIT;
  if (parent.length === 0) {
    if (["slots", "skins", "ik", "transform", "path", "physics", "constraints"].includes(field)) return [];
    if (["events", "animations"].includes(field)) return {};
  }
  if (parent.length === 1 && parent[0] === "skeleton") {
    if (field === "fps") return 30;
    if (field === "audio") return "./audio";
  }
  if (parent.length === 2 && parent[0] === "bones" && typeof parent[1] === "number") {
    return pick({ length: 0, x: 0, y: 0, rotation: 0, scaleX: 1, scaleY: 1,
      shearX: 0, shearY: 0, transform: "normal", inherit: "normal", skin: false,
      color: "989898FF" });
  }
  if (parent.length === 2 && parent[0] === "slots" && typeof parent[1] === "number") {
    return pick({ color: "FFFFFFFF", blend: "normal", attachment: null });
  }
  if (parent.length === 2 && parent[0] === "skins" && typeof parent[1] === "number") {
    return pick({ attachments: {}, bones: [], constraints: [] });
  }
  if (parent.length === 5 && parent[0] === "skins" && parent[2] === "attachments") {
    return pick({ type: "region", path: parent[4], x: 0, y: 0, rotation: 0,
      scaleX: 1, scaleY: 1, color: "FFFFFFFF" });
  }
  if (parent.length === 2 && parent[0] === "events") {
    return pick({ int: 0, float: 0, string: null, audio: null, volume: 1, balance: 0 });
  }
  if (parent[0] === "animations" && typeof parent.at(-1) === "number") {
    if (field === "time") return 0;
    const section = parent[2];
    if (section === "events") {
      const definition = record(root.events) && typeof source.name === "string"
        ? root.events[source.name] : undefined;
      const fallback = defaultFor(["events", String(source.name)], field, {}, root);
      return record(definition) && Object.hasOwn(definition, field) ? definition[field] : fallback;
    }
    if ((section === "drawOrder" || section === "draworder") && field === "offsets") return [];
    if (section === "slots" && parent[4] === "attachment" && field === "name") return null;
    if (section === "bones") {
      const type = String(parent[4] ?? "").toLowerCase();
      if (type === "rotate" && (field === "angle" || field === "value")) return 0;
      if (["translate", "shear"].includes(type) && ["x", "y"].includes(field)) return 0;
      if (type === "scale" && ["x", "y"].includes(field)) return 1;
      if (["translatex", "translatey", "shearx", "sheary"].includes(type) && field === "value") return 0;
      if (["scalex", "scaley"].includes(type) && field === "value") return 1;
    }
  }
  return OMIT;
}

function ignored(path: Path): boolean {
  // These skeleton fields are generated by the exporter from the project and
  // setup bounds; they do not represent authored rig or animation data.
  return path.length === 2 && path[0] === "skeleton"
    && ["hash", "x", "y", "width", "height"].includes(String(path[1]));
}

function sameKeyValue(left: JsonRecord, right: JsonRecord): boolean {
  const fields = new Set([...Object.keys(left), ...Object.keys(right)]);
  fields.delete("time");
  fields.delete("curve");
  return [...fields].every((field) => typeof left[field] === "number" && typeof right[field] === "number"
    ? equalNumber(left[field], right[field] as number) : Object.is(left[field], right[field]));
}

function flatCurve(curve: unknown, key: JsonRecord): boolean {
  if (curve === undefined || curve === "stepped") return true;
  if (!Array.isArray(curve)) return false;
  if (curve.length === 4 && typeof key.value === "number") {
    return equalNumber(curve[1], key.value) && equalNumber(curve[3], key.value);
  }
  if (curve.length === 8 && typeof key.x === "number" && typeof key.y === "number") {
    return equalNumber(curve[1], key.x) && equalNumber(curve[3], key.x)
      && equalNumber(curve[5], key.y) && equalNumber(curve[7], key.y);
  }
  return false;
}

function normalize(value: unknown, path: Path, root: JsonRecord): unknown {
  if (Array.isArray(value)) {
    const items = value.map((item, index) => normalize(item, [...path, index], root));
    if (path[0] === "animations" && path[2] === "bones" && path.length === 5) {
      for (let index = 0; index + 1 < items.length; index++) {
        const current = items[index];
        const next = items[index + 1];
        if (record(current) && record(next) && sameKeyValue(current, next) && flatCurve(current.curve, current)) {
          delete current.curve;
        }
      }
    }
    // A skin with no attachments, bones, or constraints is the implicit default skin.
    if (path.length === 1 && path[0] === "skins" && items.length === 1
      && record(items[0]) && Object.keys(items[0]).length === 1 && items[0].name === "default") return [];
    return items;
  }
  if (record(value)) {
    const result: JsonRecord = {};
    for (const [field, raw] of Object.entries(value)) {
      if (ignored([...path, field])) continue;
      const item = normalize(raw, [...path, field], root);
      const fallback = defaultFor(path, field, value, root);
      if (fallback !== OMIT && (isDefault(item, fallback) || isEmpty(item) && isEmpty(fallback))) continue;
      result[field] = item;
    }
    return result;
  }
  if (path.length === 2 && path[0] === "skeleton" && path[1] === "spine"
    && typeof value === "string") return value.match(/^4\.[23](?=\.|$)/)?.[0] ?? value;
  if (typeof value === "string" && ["color", "dark"].includes(String(path.at(-1)))
    && /^[0-9a-f]{6}(?:[0-9a-f]{2})?$/i.test(value)) return value.toUpperCase();
  return value;
}

function pointer(path: Path): string {
  return path.length ? `/${path.map((part) => String(part).replaceAll("~", "~0").replaceAll("/", "~1")).join("/")}` : "/";
}

function preview(value: unknown): string {
  if (value === undefined) return "<missing>";
  if (Array.isArray(value)) return `<array: ${value.length} item(s)>`;
  if (record(value)) return `<object: ${Object.keys(value).length} field(s)>`;
  const json = JSON.stringify(value);
  return json.length > 180 ? `${json.slice(0, 177)}...` : json;
}

export function compareSemanticFidelity(staged: SpineDocument, reexported: SpineDocument): SemanticFidelity {
  const left = normalize(staged.data, [], staged.data);
  const right = normalize(reexported.data, [], reexported.data);
  const differences: SemanticDifference[] = [];
  let differenceCount = 0;
  const add = (path: Path, stagedValue: unknown, reexportedValue: unknown) => {
    differenceCount++;
    if (differences.length < MAX_DIFFERENCES) {
      differences.push({ path: pointer(path), staged: preview(stagedValue), reexported: preview(reexportedValue) });
    }
  };
  const visit = (stagedValue: unknown, reexportedValue: unknown, path: Path): void => {
    if (typeof stagedValue === "number" && typeof reexportedValue === "number"
      && equalNumber(stagedValue, reexportedValue)) return;
    if (Object.is(stagedValue, reexportedValue)) return;
    if (Array.isArray(stagedValue) && Array.isArray(reexportedValue)) {
      if (stagedValue.length !== reexportedValue.length) add([...path, "length"], stagedValue.length, reexportedValue.length);
      for (let index = 0; index < Math.min(stagedValue.length, reexportedValue.length); index++) {
        visit(stagedValue[index], reexportedValue[index], [...path, index]);
      }
      return;
    }
    if (record(stagedValue) && record(reexportedValue)) {
      for (const field of [...new Set([...Object.keys(stagedValue), ...Object.keys(reexportedValue)])].sort()) {
        visit(stagedValue[field], reexportedValue[field], [...path, field]);
      }
      return;
    }
    add(path, stagedValue, reexportedValue);
  };
  visit(left, right, []);
  return { differenceCount, differences, differencesTruncated: differenceCount > differences.length,
    numericTolerance: NUMERIC_TOLERANCE,
    allowances: ["JSON object member order and whitespace", "Spine patch version and generated skeleton hash/bounds",
      "documented omitted default values and empty sections", "equivalent constant-segment curves",
      "hex color letter case",
      "absolute numeric difference below 0.0001"] };
}
