export const SERVER_NAME = "spine2d-mcp";
export const SERVER_VERSION = "0.31.1";

export type ToolStatus = "implemented" | "planned";
export type ToolBackend = "server" | "json" | "cli" | "json+cli";

export const TOOL_AREAS = ["Server", "Project understanding", "Project and files", "Skeleton",
  "Art and rig", "Animation", "Animation workflow", "Visual review", "Production"] as const;

export interface ToolCapability {
  name: string;
  status: ToolStatus;
  area: string;
  backend: ToolBackend;
  purpose: string;
}

export const TOOL_NAMES = {
  status: "spine_status",
  capabilities: "spine_capabilities",
  workflowGuide: "spine_workflow_guide",
  searchReference: "spine_search_reference",
  getReference: "spine_get_reference",
  inspectProject: "spine_inspect_project",
  searchProject: "spine_search_project",
  referenceGraph: "spine_reference_graph",
  inspectAnimation: "spine_inspect_animation",
  checkAnimation: "spine_check_animation",
  analyzePreview: "spine_analyze_preview",
  validateData: "spine_validate_data",
  inspectAssets: "spine_inspect_assets",
  projectInfo: "spine_project_info",
  createSkeleton: "spine_create_skeleton",
  createProject: "spine_create_project",
  exportData: "spine_export_data",
  exportMedia: "spine_export_media",
  importData: "spine_import_data",
  cleanupAnimations: "spine_cleanup_animations",
  previewEdit: "spine_preview_edit",
  roundTripEdit: "spine_round_trip_edit",
  retimeAnimation: "spine_retime_animation",
  cloneAnimation: "spine_clone_animation",
  reverseBoneAnimation: "spine_reverse_bone_animation",
  transformAnimation: "spine_transform_animation",
  retargetAnimation: "spine_retarget_animation",
  saveBonePose: "spine_save_bone_pose",
  applyBonePose: "spine_apply_bone_pose",
  savePose: "spine_save_pose",
  applyPose: "spine_apply_pose",
  saveMeshPose: "spine_save_mesh_pose",
  applyMeshPose: "spine_apply_mesh_pose",
  bulkKeys: "spine_bulk_keys",
  makeLoop: "spine_make_loop",
  setCurve: "spine_set_curve",
  cleanupCurves: "spine_cleanup_curves",
  setKeyframe: "spine_set_keyframe",
  deleteKeyframe: "spine_delete_keyframe",
  upsertBone: "spine_upsert_bone",
  removeBone: "spine_remove_bone",
  upsertSlot: "spine_upsert_slot",
  removeSlot: "spine_remove_slot",
  reorderSlots: "spine_reorder_slots",
  renameElement: "spine_rename_element",
  upsertConstraint: "spine_upsert_constraint",
  removeConstraint: "spine_remove_constraint",
  upsertRegionAttachment: "spine_upsert_region_attachment",
  upsertAttachment: "spine_upsert_attachment",
  removeAttachment: "spine_remove_attachment",
  setMeshGeometry: "spine_set_mesh_geometry",
  setMeshWeights: "spine_set_mesh_weights",
  upsertAnimation: "spine_upsert_animation",
  removeAnimation: "spine_remove_animation",
  upsertSkin: "spine_upsert_skin",
  removeSkin: "spine_remove_skin",
  upsertEvent: "spine_upsert_event",
  removeEvent: "spine_remove_event",
  setSkeletonMetadata: "spine_set_skeleton_metadata",
  packAtlas: "spine_pack_atlas",
  unpackAtlas: "spine_unpack_atlas",
  manageExportProfile: "spine_manage_export_profile",
  runExportProfile: "spine_run_export_profile",
  batchJob: "spine_batch_job",
  generateMotion: "spine_generate_motion",
  webPlayerPreview: "spine_web_player_preview",
  startRigReview: "spine_start_rig_review",
  saveRigDraft: "spine_save_rig_draft",
  validateRigManifest: "spine_validate_rig_manifest",
  buildRigFromLandmarks: "spine_build_rig_from_landmarks",
  previewRig: "spine_preview_rig",
  analyzeMotionQuality: "spine_analyze_motion_quality",
  commitEdit: "spine_commit_edit",
  renderPreview: "spine_render_preview",
  renderStagedEdit: "spine_render_staged_edit",
  comparePreviews: "spine_compare_previews",
  contactSheet: "spine_contact_sheet",
} as const;

export const IMPLEMENTED_TOOLS: readonly ToolCapability[] = [
  {
    name: TOOL_NAMES.status,
    status: "implemented",
    area: "Server",
    backend: "server",
    purpose: "Report server identity and integration state.",
  },
  {
    name: TOOL_NAMES.capabilities,
    status: "implemented",
    area: "Server",
    backend: "server",
    purpose: "List implemented and planned tools.",
  },
  { name: TOOL_NAMES.workflowGuide, status: "implemented", area: "Server", backend: "server", purpose: "Choose a short end-to-end workflow and its required inputs." },
  { name: TOOL_NAMES.searchReference, status: "implemented", area: "Server", backend: "server", purpose: "Search task-specific reference pages and return fetchable MCP resource URIs." },
  { name: TOOL_NAMES.getReference, status: "implemented", area: "Server", backend: "server", purpose: "Fetch one task-specific reference page as Markdown." },
  { name: TOOL_NAMES.inspectProject, status: "implemented", area: "Project understanding", backend: "json", purpose: "Summarize skeletons, rig elements, assets, and timelines." },
  { name: TOOL_NAMES.searchProject, status: "implemented", area: "Project understanding", backend: "json", purpose: "Search named project elements without returning full JSON." },
  { name: TOOL_NAMES.referenceGraph, status: "implemented", area: "Project understanding", backend: "json", purpose: "Find known Spine 4.2 and 4.3 references to an element." },
  { name: TOOL_NAMES.inspectAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Inspect an animation and query keys within a time range." },
  { name: TOOL_NAMES.checkAnimation, status: "implemented", area: "Visual review", backend: "json", purpose: "Report structural animation issues and optionally analyze a rendered preview." },
  { name: TOOL_NAMES.analyzePreview, status: "implemented", area: "Visual review", backend: "server", purpose: "Analyze rendered frames for blanks, visible-area jumps, and optional canvas-edge contact." },
  { name: TOOL_NAMES.validateData, status: "implemented", area: "Project understanding", backend: "json", purpose: "Validate skeleton JSON, references, mesh data, and timelines." },
  { name: TOOL_NAMES.inspectAssets, status: "implemented", area: "Production", backend: "json", purpose: "Find missing and unused images and missing atlas pages." },
  { name: TOOL_NAMES.projectInfo, status: "implemented", area: "Project and files", backend: "cli", purpose: "Read project or data information through Spine CLI." },
  { name: TOOL_NAMES.createSkeleton, status: "implemented", area: "Skeleton", backend: "json", purpose: "Create minimal Spine 4.2 or 4.3 skeleton JSON." },
  { name: TOOL_NAMES.createProject, status: "implemented", area: "Project and files", backend: "json+cli", purpose: "Create skeleton JSON and a new Spine project through CLI import." },
  { name: TOOL_NAMES.exportData, status: "implemented", area: "Project and files", backend: "cli", purpose: "Export reimportable JSON with nonessential data." },
  { name: TOOL_NAMES.exportMedia, status: "implemented", area: "Project and files", backend: "cli", purpose: "Export images or video from saved Spine media settings into a new directory." },
  { name: TOOL_NAMES.importData, status: "implemented", area: "Project and files", backend: "json+cli", purpose: "Import validated JSON into a new Spine project." },
  { name: TOOL_NAMES.cleanupAnimations, status: "implemented", area: "Project and files", backend: "cli", purpose: "Clean all project animations through Spine CLI into a new project file." },
  { name: TOOL_NAMES.previewEdit, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage an atomic edit batch with diff and validation." },
  { name: TOOL_NAMES.roundTripEdit, status: "implemented", area: "Animation workflow", backend: "json+cli", purpose: "Export with nonessential data, stage edits, import and re-export a new project, validate it, and compare rendered frames." },
  { name: TOOL_NAMES.retimeAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage a whole-animation retime." },
  { name: TOOL_NAMES.cloneAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Create a new animation variant with all key and curve times transformed." },
  { name: TOOL_NAMES.reverseBoneAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Reverse continuous bone motion and event timing into a new animation." },
  { name: TOOL_NAMES.transformAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Mirror, combine, retime, reverse, or extract animation variants." },
  { name: TOOL_NAMES.retargetAnimation, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Transfer a clip between compatible skeletons with explicit element mappings and a staged compatibility report." },
  { name: TOOL_NAMES.saveBonePose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Capture sampled bone transform timeline values as a reusable session pose." },
  { name: TOOL_NAMES.applyBonePose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage a bone pose in a compatible skeleton with blending and bone mapping." },
  { name: TOOL_NAMES.savePose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Capture numeric bone and slot attachment state as a reusable session pose." },
  { name: TOOL_NAMES.applyPose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage a saved pose with bone blending, mirroring, offsets, and compatible slot mapping." },
  { name: TOOL_NAMES.saveMeshPose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Sample deform timelines into a reusable mesh pose with geometry fingerprints." },
  { name: TOOL_NAMES.applyMeshPose, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage a compatible mesh pose with mapping and numeric blending." },
  { name: TOOL_NAMES.bulkKeys, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Stage bulk key movement, scaling, duplication, deletion, numeric offsets, or quantization." },
  { name: TOOL_NAMES.makeLoop, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Close loop end poses and ease supported scalar seams." },
  { name: TOOL_NAMES.setCurve, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Set linear, stepped, or Bézier easing on an existing bone transform key." },
  { name: TOOL_NAMES.cleanupCurves, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Simplify bone keys with a motion error bound or smooth their interpolation." },
  { name: TOOL_NAMES.setKeyframe, status: "implemented", area: "Animation", backend: "json", purpose: "Stage a type-checked key insertion or update on a supported timeline." },
  { name: TOOL_NAMES.deleteKeyframe, status: "implemented", area: "Animation", backend: "json", purpose: "Stage deletion of a selected animation key and prune an empty timeline." },
  { name: TOOL_NAMES.upsertBone, status: "implemented", area: "Skeleton", backend: "json", purpose: "Create or update a bone setup pose." },
  { name: TOOL_NAMES.removeBone, status: "implemented", area: "Skeleton", backend: "json", purpose: "Remove an unused bone and remap later weighted bone indices." },
  { name: TOOL_NAMES.upsertSlot, status: "implemented", area: "Skeleton", backend: "json", purpose: "Create or update a slot setup pose." },
  { name: TOOL_NAMES.removeSlot, status: "implemented", area: "Skeleton", backend: "json", purpose: "Remove an unused slot after checking its references." },
  { name: TOOL_NAMES.reorderSlots, status: "implemented", area: "Skeleton", backend: "json", purpose: "Reorder setup slots with optional preservation of global draw-order animation keys." },
  { name: TOOL_NAMES.renameElement, status: "implemented", area: "Skeleton", backend: "json", purpose: "Rename a rig, animation, or slot-wide attachment name and update known references." },
  { name: TOOL_NAMES.upsertConstraint, status: "implemented", area: "Art and rig", backend: "json", purpose: "Create or update a Professional IK, transform, path, or physics constraint." },
  { name: TOOL_NAMES.removeConstraint, status: "implemented", area: "Art and rig", backend: "json", purpose: "Remove an unused constraint from its version-specific section." },
  { name: TOOL_NAMES.upsertRegionAttachment, status: "implemented", area: "Art and rig", backend: "json", purpose: "Create or update a region attachment." },
  { name: TOOL_NAMES.upsertAttachment, status: "implemented", area: "Art and rig", backend: "json", purpose: "Create or update a typed attachment." },
  { name: TOOL_NAMES.removeAttachment, status: "implemented", area: "Art and rig", backend: "json", purpose: "Remove an unused attachment after checking references." },
  { name: TOOL_NAMES.setMeshGeometry, status: "implemented", area: "Art and rig", backend: "json", purpose: "Set unweighted mesh geometry with dependency checks." },
  { name: TOOL_NAMES.setMeshWeights, status: "implemented", area: "Art and rig", backend: "json", purpose: "Set mesh influences by bone name." },
  { name: TOOL_NAMES.upsertAnimation, status: "implemented", area: "Animation", backend: "json", purpose: "Create an empty animation for key authoring." },
  { name: TOOL_NAMES.removeAnimation, status: "implemented", area: "Animation", backend: "json", purpose: "Remove one named animation and its timelines." },
  { name: TOOL_NAMES.upsertSkin, status: "implemented", area: "Art and rig", backend: "json", purpose: "Create or update a skin without replacing its attachments." },
  { name: TOOL_NAMES.removeSkin, status: "implemented", area: "Art and rig", backend: "json", purpose: "Remove an unused named skin after checking references." },
  { name: TOOL_NAMES.upsertEvent, status: "implemented", area: "Art and rig", backend: "json", purpose: "Create or update an animation event definition." },
  { name: TOOL_NAMES.removeEvent, status: "implemented", area: "Art and rig", backend: "json", purpose: "Remove an event definition after checking its keys." },
  { name: TOOL_NAMES.setSkeletonMetadata, status: "implemented", area: "Skeleton", backend: "json", purpose: "Set image path, audio path, or skeleton frame rate." },
  { name: TOOL_NAMES.packAtlas, status: "implemented", area: "Project and files", backend: "cli", purpose: "Pack PNG images into an atlas without overwriting existing outputs." },
  { name: TOOL_NAMES.unpackAtlas, status: "implemented", area: "Project and files", backend: "cli", purpose: "Unpack atlas PNG images into a new directory." },
  { name: TOOL_NAMES.manageExportProfile, status: "implemented", area: "Production", backend: "server", purpose: "Save, inspect, list, and delete portable export setting snapshots with editor/runtime checks." },
  { name: TOOL_NAMES.runExportProfile, status: "implemented", area: "Production", backend: "cli", purpose: "Run saved data, media, and atlas exports together with an output manifest." },
  { name: TOOL_NAMES.batchJob, status: "implemented", area: "Production", backend: "json", purpose: "Stage or commit one animation operation across selected projects with progress and cancellation." },
  { name: TOOL_NAMES.generateMotion, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Generate a parameterized idle, breathing, blink, walk, run, recoil, or follow-through clip." },
  { name: TOOL_NAMES.webPlayerPreview, status: "implemented", area: "Visual review", backend: "server", purpose: "Create a standalone Spine Web Player HTML preview with embedded skeleton, atlas, and textures." },
  { name: TOOL_NAMES.startRigReview, status: "implemented", area: "Art and rig", backend: "server", purpose: "Inventory PNGs and open a two-view landmark and assembly editor." },
  { name: TOOL_NAMES.saveRigDraft, status: "implemented", area: "Art and rig", backend: "server", purpose: "Save a fully connected assembly draft before visual review and confirmation." },
  { name: TOOL_NAMES.validateRigManifest, status: "implemented", area: "Art and rig", backend: "json", purpose: "Check landmark graph, PNG hashes, canvas bounds, and visual warnings." },
  { name: TOOL_NAMES.buildRigFromLandmarks, status: "implemented", area: "Art and rig", backend: "json+cli", purpose: "Compile a confirmed rig to new Spine JSON and optionally import a native project." },
  { name: TOOL_NAMES.previewRig, status: "implemented", area: "Visual review", backend: "json+cli", purpose: "Render setup and bend overlays and, when available, a Spine Web Player preview." },
  { name: TOOL_NAMES.analyzeMotionQuality, status: "implemented", area: "Visual review", backend: "json+cli", purpose: "Check rig-attached plant, touch, and roll contacts against a surface, with compatible visual contact estimates." },
  { name: TOOL_NAMES.commitEdit, status: "implemented", area: "Animation workflow", backend: "json", purpose: "Commit a staged edit with backup and manifest." },
  { name: TOOL_NAMES.renderPreview, status: "implemented", area: "Visual review", backend: "cli", purpose: "Render PNG animation frames from saved Spine export settings." },
  { name: TOOL_NAMES.renderStagedEdit, status: "implemented", area: "Visual review", backend: "json+cli", purpose: "Render staged animation changes before commit." },
  { name: TOOL_NAMES.comparePreviews, status: "implemented", area: "Visual review", backend: "json+cli", purpose: "Compare staged preview frames with a contact sheet and pixel difference measurements." },
  { name: TOOL_NAMES.contactSheet, status: "implemented", area: "Visual review", backend: "server", purpose: "Create a sampled contact sheet from an existing preview sequence." },
];

export const PLANNED_TOOLS: readonly ToolCapability[] = [
  { name: "spine_capture_constraint_pose", status: "planned", area: "Animation workflow", backend: "json", purpose: "Capture and transfer sampled constraint channels across compatible skeletons." },
];

export const TOOL_CATALOG: readonly ToolCapability[] = [
  ...IMPLEMENTED_TOOLS,
  ...PLANNED_TOOLS,
];
